apiVersion: v1
kind: Secret
metadata:
  name: secret-hackaton
type: Opaque
data:
  APPLICATION_NAME: bWVkaWMtYXBwb2ludG1lbnQ=
  APPLICATION_HOST: MC4wLjAuMA==
  APPLICATION_PORT: ODAwMA==
  ENVIRONMENT: ZGV2
  WORKERS: MQ==
  TIMEOUT_GRACEFUL_SHUTDOWN: NQ==
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: JHEwNylqWkdbWFtNTSp9ezhxMiV9eWZjWVE4QQ==
  DATABASE_HOST: cmRzLWhhY2thdGhvbi5jbDZtMHVrbTZheGQudXMtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DATABASE_PORT: NTQzMg==
  DATABASE_NAME: cG9zdGdyZXM=
  AWS_SIMPLE_STORAGE_SERVICE_BUCKET_NAME: aGFja2F0aG9uLWczOA==
  AWS_SIMPLE_NOTIFICATION_SERVICE_TOPIC_NAME: aGFja2F0aG9u